default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEV", "dana_helpdesk_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "dana_helpdesk_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") %>
